version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./src:/tp5mai/src
      - /app/node_modules
      - /app/node_modules/react-scripts
    container_name: tp5mai
    restart: always

